{% set name = "oauth2" %}
{% set version = "1.9.0.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oauth2-{{ version }}.tar.gz
  sha256: c006a85e7c60107c7cc6da1b184b5c719f6dd7202098196dfa6e55df669b59bf

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - httplib2
    - python >={{ python_min }}

test:
  imports:
    - oauth2
    - oauth2.clients
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/joestump/python-oauth2
  summary: library for OAuth version 1.9
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
